#!/usr/bin/zsh
#This function is used to cleanly exit any script. It does this displaying a
# given error message, and exiting with an error code.
function error_exit {
    echo
    echo "$@"
    exit 1
}
#Trap the killer signals so that we can exit with a good message.
trap "error_exit 'Received signal SIGHUP'" SIGHUP
trap "error_exit 'Received signal SIGINT'" SIGINT
trap "error_exit 'Received signal SIGTERM'" SIGTERM

#Alias the function so that it will print a message with the following format:
#prog-name(@line#): message
#We have to explicitly allow aliases, we do this because they make calling the
#function much easier (see example).
shopt -s expand_aliases
alias die='error_exit "Error ${0}(@`echo $(( $LINENO - 1 ))`):"'

 if [ $# -eq 0 ]; then
  echo "I need a device number"
  exit 1
fi

nvidia-docker /
	run /
	-it /
	--volume=$PWD:/root/notebook /
	--volume=/store/experimentalResults:/root/save /
	--volume=/home/dewoller/docker-torch/data:/root/data /
	--name Torch_GPU$1 /
	--hostname Torch_GPU$1 /
	torch /
	/bin/bash
